channels:
- conda-forge
dependencies:
- python=3.9.5
- pip<=21.2.4
- pip:
  - mlflow<3,>=2.1
  - cloudpickle==2.2.1
  - psutil==5.8.0
  - scikit-learn==1.2.1
  - typing-extensions==3.10.0.2
name: mlflow-env
